	<?php include 'modules/carousel.php'; ?>
  <?php include 'modules/full-width.php'; ?>
  <?php include 'modules/full-width-image.php'; ?>
  <?php include 'modules/half-width.php'; ?>
  <?php include 'modules/four-up.php'; ?>
  <?php include 'modules/slash.php'; ?>
  <?php include 'modules/full-width-carousel.php'; ?>
  <?php include 'modules/typeform.php'; ?>
  <?php include 'modules/four-up-lightbox.php'; ?>
  <?php include 'modules/half-width-left-list.php'; ?>
  <?php include 'modules/four-up-carousel.php'; ?>
  <?php include 'modules/alternate-header.php'; ?>
